# Use root/example as user/password credentials
version: '3.1'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tablatura_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: tablatura_password
      ME_CONFIG_MONGODB_URL: mongodb://tablatura_user:tablatura_password@mongo:27017/

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tablatura_user
      MONGO_INITDB_ROOT_PASSWORD: tablatura_password
      MONGO_INITDB_DATABASE: tablatura
    ports:
      - "27017:27017"
    volumes:
      - mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongodb_server_data:

  